kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker:linux-arm64
  settings:
    repo: h3rj4n/prometheus
    tags:
      - latest
      - '2.12.0'
    build_args:
      - VERSION=2.12.0
    #dry-run: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
